#!/usr/bin/env python3

"""
Script Name: stringtie2utr.py
Description: This script decorates a gtf file with genes generated by AUGUSTUS,
             BRAKER, or TSEBRA, which UTR features from a stringtie gtf file.
Author: Katharina J. Hoff
Email: katharina.hoff@uni-greifswald.de
Date: September 29th 2023

Copyright (C) The year of copyright, Katharina J. Hoff, University of Greifswald

This program is free software; you can redistribute it and/or modify
it under the terms of the Artistic License.
"""

import argparse
import bisect
import re
import sys
from intervaltree import IntervalTree, Interval


def read_gtf(gtf_file):
    """
    Reads a GTF file and extracts gene and non-gene features.

    Args:
    - gtf_file (str): Path to the GTF file.

    Returns:
    tuple: (non_gene_dict, gene_dict, tx_to_gene_dict, tx_dict) where:
    - non_gene_dict (dict): Dictionary with transcript IDs as keys and lists of non-gene feature lines as values.
    - gene_dict (dict): Dictionary with gene IDs extracted from the last column of gene feature lines as keys and the corresponding gene line as value.
    - tx_to_gene_dict (dict): Dictionary with transcript IDs as keys and the corresponding gene ID as value, extracted from the last column of transcript feature lines.
    - tx_dict (dict): Dictionary with transcript IDs as keys and the corresponding transcript line as value. The entire last column is used as the transcript ID.
    """
    non_gene_dict = {}
    gene_dict = {}
    tx_to_gene_dict = {}
    tx_dict = {}
    transcript_id_pattern = re.compile(r'transcript_id "([^"]+)"')
    gene_id_pattern = re.compile(r'gene_id "([^"]+)"')

    with open(gtf_file, 'r') as f:
        for line in f:
            if not line.startswith("#"):
                fields = line.strip().split("\t")
                feature_type = fields[2]
                last_field = fields[-1]

                if feature_type == "gene":
                    gene_dict[last_field] = line.strip()  # Use the entire last field as gene_id
                elif feature_type == "transcript":
                    tx_dict[last_field] = line.strip()  # Use the entire last field as transcript_id
                else:
                    transcript_id_match = transcript_id_pattern.search(last_field)
                    gene_id_match = gene_id_pattern.search(last_field)
                    gene_id = None
                    transcript_id = None
                    if transcript_id_match:
                        transcript_id = transcript_id_match.group(1)
                    if gene_id_match:
                        gene_id = gene_id_match.group(1)
                    if transcript_id:  # Ensure we have a transcript ID
                        non_gene_dict.setdefault(transcript_id, []).append(line.strip())
                        if transcript_id not in tx_to_gene_dict:
                            tx_to_gene_dict[transcript_id] = gene_id

    return non_gene_dict, gene_dict, tx_to_gene_dict, tx_dict




def add_intron_features(gtf_dict):
    """
    Adds intron feature lines based on the exon feature lines.
    
    Args:
    - gtf_dict (dict): Dictionary with transcript_id as key and a list of 
    GTF entries as values.

    Returns:
    dict: Updated GTF dictionary with intron feature lines added.
    """
    
    for transcript_id, entries in gtf_dict.items():
        sorted_exons = sorted([entry for entry in entries if entry.split('\t')[2] == 'exon'], key=lambda x: int(x.split('\t')[3]))
        
        new_entries = []
        for i in range(len(sorted_exons) - 1):
            curr_exon = sorted_exons[i]
            next_exon = sorted_exons[i + 1]
            
            curr_end = int(curr_exon.split('\t')[4])
            next_start = int(next_exon.split('\t')[3])
            
            if next_start - curr_end > 1:
                # Construct intron feature line based on exon line, but replace the feature name with "intron"
                intron_line = curr_exon.split('\t')
                intron_line[2] = 'intron'
                intron_line[3] = str(curr_end + 1)
                intron_line[4] = str(next_start - 1)
                
                # Remove exon_number attribute
                intron_line[8] = re.sub(r'exon_number "\d+";', '', intron_line[8]).strip()

                # Add the intron line to new entries
                new_entries.append('\t'.join(intron_line))

        # Extend the original entries with new intron feature lines
        gtf_dict[transcript_id].extend(new_entries)

    return gtf_dict



def create_introns_hash(non_gene_dict):
    """
    Collects the intron chain of every transcript.

    Earlier versions keyed the dictionary by intron and kept one transcript
    per intron, so an intron shared by alternative transcripts of a gene was
    recorded for the last one only. The other transcripts were then matched
    on their remaining introns alone, and a StringTie transcript missing one
    of their introns matched; its exons became UTRs inside those introns.

    Args:
    - non_gene_dict (dict): Dictionary with transcript_id as key and a list of
    GTF entries as values.

    Returns:
    dict: Dictionary with transcript IDs as keys and the set of their intron
    keys (seqname_start_end_strand) as values; transcripts without introns
    are absent.
    """

    introns_hash = {}

    for transcript_id, entries in non_gene_dict.items():
        for entry in entries:
            # Check if the feature is an intron
            if entry.split('\t')[2] == 'intron':
                seqname = entry.split('\t')[0]
                start = entry.split('\t')[3]
                end = entry.split('\t')[4]
                strand = entry.split('\t')[6]
                intron_key = f"{seqname}_{start}_{end}_{strand}"
                introns_hash.setdefault(transcript_id, set()).add(intron_key)

    return introns_hash


def find_matching_transcripts(intron_hash1, intron_hash2):
    """
    Find matching transcript IDs based on intron patterns: a transcript of the
    first set matches every transcript of the second set whose intron chain
    contains all of its introns. This only works for multi-exon genes.

    Args:
    - intron_hash1 (dict): transcript ID -> set of intron keys, first dataset (create_introns_hash).
    - intron_hash2 (dict): transcript ID -> set of intron keys, second dataset.

    Returns:
    dict: Dictionary with transcript IDs from intron_hash1 as keys and lists of matching transcript IDs from intron_hash2 as values.
    """

    # transcripts of the second set per intron, so that only candidates sharing
    # the first intron are checked
    by_intron = {}
    for transcript2, introns2 in intron_hash2.items():
        for intron in introns2:
            by_intron.setdefault(intron, []).append(transcript2)

    matching_transcripts = {}

    for transcript1, introns1 in intron_hash1.items():
        first = next(iter(introns1))
        matches = set()
        for transcript2 in by_intron.get(first, []):
            if introns1 <= intron_hash2[transcript2]:
                matches.add(transcript2)

        if matches:
            matching_transcripts[transcript1] = list(matches)

    return matching_transcripts


def find_single_exon_genes(non_gene_dict):
    """
    Find single exon genes in non_gene_dict.
    
    Args:
    - non_gene_dict (dict): Dictionary with transcript_id as key and a list of 
    GTF entries as values.

    Returns:
    dict: List of transcript IDs for single exon genes.
    """
    
    single_exon_genes = {}
    
    for transcript_id, entries in non_gene_dict.items():
        # Check if the transcript has only one exon
        if len([entry for entry in entries if entry.split('\t')[2] == 'exon']) == 1:
            single_exon_genes[transcript_id] = True

    return single_exon_genes

def tx_len(non_gene_dict):
    """
    Calculate the length of each transcript.

    Args:
    - non_gene_dict (dict): Dictionary with transcript_id as key and a list of 
    GTF entries as values.

    Returns:
    dict: Dictionary with transcript IDs as keys and their lengths as values.
    """
    
    transcript_lengths = {}

    for transcript_id, entries in non_gene_dict.items():
        total_length = 0
        
        for entry in entries:
            fields = entry.split('\t')
            start = int(fields[3])
            end = int(fields[4])
            
            total_length += (end - start + 1)  # +1 because both start and end are inclusive

        transcript_lengths[transcript_id] = total_length

    return transcript_lengths


def select_longest_tx(matched_transcripts, tx_lens_stringtie):
    """
    For each key in matched_transcripts, select the longest transcript based on lengths provided in tx_lens_stringtie.

    Args:
    - matched_transcripts (dict): Dictionary with keys as transcript IDs and values as lists of matching transcript IDs.
    - tx_lens_stringtie (dict): Dictionary with transcript IDs as keys and their lengths as values.

    Returns:
    dict: Dictionary with keys from matched_transcripts and values as the IDs of the longest transcripts.
    """
    
    selected_transcripts = {}

    for original_tx, matched_tx_list in matched_transcripts.items():
        # Find the longest transcript in the matched_tx_list
        longest_tx = max(matched_tx_list, key=lambda tx: tx_lens_stringtie.get(tx, 0))

        selected_transcripts[original_tx] = longest_tx

    return selected_transcripts


def overlap(exon_start, exon_end, cds_start, cds_end):
    """Check if exon overlaps with CDS."""
    return exon_start <= cds_end and exon_end >= cds_start


def same_locus(feature, reference):
    """True if two GTF lines share sequence name and strand (issue #62)."""
    f = feature.split('\t')
    r = reference.split('\t')
    return f[0] == r[0] and f[6] == r[6]


def clip_exons(exons, lo, hi):
    """Clip exon lines to [lo, hi] (None = unbounded); drop exons outside."""
    clipped = []
    for e in exons:
        ef = e.split('\t')
        new_start = int(ef[3]) if lo is None else max(int(ef[3]), lo)
        new_end = int(ef[4]) if hi is None else min(int(ef[4]), hi)
        if new_start <= new_end:
            ef[3] = str(new_start)
            ef[4] = str(new_end)
            clipped.append('\t'.join(ef))
    return clipped


def neighbour_bounds(tsebra_gtf, tx_to_gene_dict, supported_tx):
    """
    Region each BRAKER transcript's UTRs may occupy without running into a
    transcript-supported gene (issue #29 follow-up).

    StringTie often joins adjacent genes on the same strand into one read-through
    transcript; without a limit, the neighbour gene becomes UTR. Only neighbours
    with their own match in a StringTie assembly (supported_tx) stop a UTR;
    ab initio neighbours may be wrong and do not. Neighbours that overlap the
    transcript, and other transcripts of the same gene, are ignored.

    Must be called before merge_features, which extends the transcripts.

    Args:
    - tsebra_gtf (dict): transcript ID -> list of GTF feature lines (no UTRs yet).
    - tx_to_gene_dict (dict): transcript ID -> gene ID.
    - supported_tx (iterable): transcript IDs with a StringTie match.

    Returns:
    dict: transcript ID -> (lo, hi), first and last position a UTR may cover;
          None where there is no supported neighbour on that side.
    """
    spans = {}
    for tx_id, features in tsebra_gtf.items():
        if not features:
            continue
        f0 = features[0].split('\t')
        spans[tx_id] = (f0[0], f0[6],
                        min(int(f.split('\t')[3]) for f in features),
                        max(int(f.split('\t')[4]) for f in features))

    by_locus = {}
    for tx_id in supported_tx:
        if tx_id in spans:
            seq, strand, start, end = spans[tx_id]
            by_locus.setdefault((seq, strand), []).append(
                (start, end, tx_to_gene_dict.get(tx_id)))
    index = {}
    for key, items in by_locus.items():
        by_end = sorted(items, key=lambda x: x[1])
        by_start = sorted(items, key=lambda x: x[0])
        index[key] = (by_end, [x[1] for x in by_end],
                      by_start, [x[0] for x in by_start])

    bounds = {}
    for tx_id, (seq, strand, start, end) in spans.items():
        if (seq, strand) not in index:
            continue
        by_end, ends, by_start, starts = index[(seq, strand)]
        gene_id = tx_to_gene_dict.get(tx_id)
        lo = hi = None
        # nearest supported neighbour ending left of this transcript
        i = bisect.bisect_left(ends, start) - 1
        while i >= 0:
            if by_end[i][2] != gene_id:
                lo = by_end[i][1] + 1
                break
            i -= 1
        # nearest supported neighbour starting right of this transcript
        i = bisect.bisect_right(starts, end)
        while i < len(by_start):
            if by_start[i][2] != gene_id:
                hi = by_start[i][0] - 1
                break
            i += 1
        if lo is not None or hi is not None:
            bounds[tx_id] = (lo, hi)
    return bounds


def merge_features(tsebra_gtf, stringtie_gtf, selected_transcripts, max_utr_extension=5000,
                   bounds=None):
    for tsebra_tx, stringtie_tx in selected_transcripts.items():
        # Retrieve features for current transcripts
        tsebra_features = tsebra_gtf[tsebra_tx]
        stringtie_exons = [f for f in stringtie_gtf[stringtie_tx] if f.split('\t')[2] == 'exon']
        tsebra_cds_features = [f for f in tsebra_features if f.split('\t')[2] == 'CDS']

        # When StringTie is run per-scaffold and outputs are merged, MSTRG IDs
        # can collide: the same transcript_id appears on multiple scaffolds and
        # read_gtf() groups all those features under one key. Only keep StringTie
        # exons that are on the same scaffold and strand as the BRAKER transcript.
        if tsebra_features:
            stringtie_exons = [e for e in stringtie_exons
                               if same_locus(e, tsebra_features[0])]

        # Clip StringTie exons so they cannot extend more than max_utr_extension bp
        # beyond the BRAKER CDS boundaries.  Very long StringTie exons arise from
        # polycistronic (plastid/mitochondrial) or read-through assemblies; without
        # this cap they generate UTR annotations spanning tens of kilobases.
        if tsebra_cds_features:
            cds_min = min(int(f.split('\t')[3]) for f in tsebra_cds_features)
            cds_max = max(int(f.split('\t')[4]) for f in tsebra_cds_features)
            stringtie_exons = clip_exons(stringtie_exons, cds_min - max_utr_extension,
                                         cds_max + max_utr_extension)

        # Stop UTRs at the nearest transcript-supported neighbour gene (#29).
        if bounds and tsebra_tx in bounds:
            stringtie_exons = clip_exons(stringtie_exons, *bounds[tsebra_tx])

        # For single-exon BRAKER transcripts, only accept StringTie exons that overlap
        # the BRAKER exon. Single-exon genes are matched by position overlap, not by
        # intron identity, so a multi-exon StringTie transcript can be selected whose
        # distant exons have nothing to do with this gene's UTR structure.
        tsebra_exon_features = [f for f in tsebra_features if f.split('\t')[2] == 'exon']
        if len(tsebra_exon_features) == 1:
            be = tsebra_exon_features[0].split('\t')
            be_start, be_end = int(be[3]), int(be[4])
            stringtie_exons = [e for e in stringtie_exons
                               if overlap(int(e.split('\t')[3]), int(e.split('\t')[4]),
                                          be_start, be_end)]

        kept_exons = []
        for exon in stringtie_exons:
            exon_parts = exon.split('\t')
            exon_start, exon_end = int(exon_parts[3]), int(exon_parts[4])

            # Flag to determine if current exon should be merged
            merge_exon = True

            for cds in tsebra_cds_features:
                cds_parts = cds.split('\t')
                cds_start, cds_end = int(cds_parts[3]), int(cds_parts[4])

                if overlap(exon_start, exon_end, cds_start, cds_end):
                    # Exon overlaps with CDS. Check the length condition.
                    if exon_end - exon_start + 1 < cds_end - cds_start + 1:
                        merge_exon = False
                        break

            if merge_exon:
                kept_exons.append(exon)

        # UTR exons on a side of the CDS are used only if a kept StringTie exon
        # contains that end of the CDS. When the exon over the outermost CDS
        # segment was dropped above (shorter than the segment), the exons
        # further out would become UTRs joined to the CDS by an intron
        # StringTie does not have.
        if tsebra_cds_features:
            spans = [(int(e.split('\t')[3]), int(e.split('\t')[4])) for e in kept_exons]
            left_ok = any(s <= cds_min <= e for s, e in spans)
            right_ok = any(s <= cds_max <= e for s, e in spans)
            kept_exons = [ex for ex, (s, e) in zip(kept_exons, spans)
                          if (left_ok or e >= cds_min) and (right_ok or s <= cds_max)]

        # Add the exons that passed the checks to tsebra_features
        tsebra_features.extend(kept_exons)

        # Update the tsebra_gtf dictionary with new features
        tsebra_gtf[tsebra_tx] = tsebra_features

    return tsebra_gtf


def _make_utr_feature(fields, utr_type, utr_start, utr_end):
    """
    Create a UTR feature line with explicit start/end coordinates.

    Avoids the string-replace bug where coordinates could be replaced
    in the wrong column or produce inverted coordinates (start > end).

    Returns None if the resulting UTR would be invalid (start > end).
    """
    if utr_start > utr_end:
        return None
    new_fields = list(fields)
    new_fields[2] = utr_type
    new_fields[3] = str(utr_start)
    new_fields[4] = str(utr_end)
    return "\t".join(new_fields)


def coding_intervals(features):
    """
    Coding intervals (start, end) of one transcript: its CDS and stop_codon
    lines.

    GTF2.2 keeps the stop codon out of the CDS lines and gives it a stop_codon
    line. GeneMark transcripts in braker.gtf can lack the stop_codon line while
    their exon still covers the stop codon: when a transcript has no stop_codon
    line and a predictor exon ends exactly 3 bp after the last CDS on the 3'
    side, those 3 bp are coding, not UTR.
    """
    coding = []
    has_stop = False
    strand = None
    for f in features:
        fields = f.split('\t')
        if fields[2] in ("CDS", "stop_codon"):
            coding.append((int(fields[3]), int(fields[4])))
            strand = fields[6]
            has_stop = has_stop or fields[2] == "stop_codon"
    if coding and not has_stop:
        cds_min = min(s for s, _ in coding)
        cds_max = max(e for _, e in coding)
        for f in features:
            fields = f.split('\t')
            if fields[2] != "exon" or "StringTie" in fields[1]:
                continue
            s, e = int(fields[3]), int(fields[4])
            if strand == "+" and s <= cds_max and e == cds_max + 3:
                coding.append((cds_max + 1, e))
                break
            if strand == "-" and e >= cds_min and s == cds_min - 3:
                coding.append((s, cds_min - 1))
                break
    return coding


def _merge_utrs(utr_features):
    """Join UTR features of the same type that overlap or touch each other."""
    merged = []
    for feature in sorted(utr_features, key=lambda x: (x.split('\t')[2], int(x.split('\t')[3]))):
        fields = feature.split('\t')
        start, end = int(fields[3]), int(fields[4])
        if merged:
            prev = merged[-1].split('\t')
            if prev[2] == fields[2] and start <= int(prev[4]) + 1:
                prev[4] = str(max(int(prev[4]), end))
                merged[-1] = '\t'.join(prev)
                continue
        merged.append(feature)
    return merged


def compute_utr_features(tsebra_gtf):
    """
    Compute the UTR features for each transcript in tsebra_gtf based on strand information.

    After merge_features, a transcript holds its predictor features and the
    StringTie exons chosen for it. The coding region is the CDS plus the stop
    codon (coding_intervals). Every exon, from the predictor or from StringTie,
    that overlaps the coding region contributes its parts before and after the
    coding region as UTR features; a StringTie exon that overlaps the coding
    region is then dropped, its UTR parts replace it. A StringTie exon outside
    the coding region becomes a UTR feature as a whole, its type given by its
    position relative to the coding region and the strand. UTR features of
    one type that overlap or touch are joined.

    History (github.com/Gaius-Augustus/BRAKER/issues/867, BRAKER4 issue #29):
    the first version replaced coordinates by string replace and dropped a
    StringTie exon only when it started at the same position as a neighbouring
    feature. A StringTie exon starting inside the CDS and ending behind it
    (single-exon genes) was kept and renamed as a whole, which gave a second
    three_prime_UTR running from inside the CDS to the transcript end.

    Args:
    - tsebra_gtf (dict): Dictionary with transcript IDs as keys and lists of GTF feature lines as values.

    Returns:
    dict: Updated tsebra_gtf dictionary with UTR features added.
    """
    for transcript_id, features in tsebra_gtf.items():
        features.sort(key=lambda x: int(x.split('\t')[3]))

        coding = coding_intervals(features)
        if not coding:
            # nothing to decorate; StringTie exons cannot be placed without a CDS
            tsebra_gtf[transcript_id] = [
                f for f in features
                if not (f.split('\t')[2] == "exon" and "StringTie" in f.split('\t')[1])]
            continue
        cds_min = min(s for s, _ in coding)
        cds_max = max(e for _, e in coding)

        kept = []
        utr_features = []
        for feature in features:
            fields = feature.split('\t')
            if fields[2] != "exon":
                kept.append(feature)
                continue
            start, end, strand = int(fields[3]), int(fields[4]), fields[6]
            from_stringtie = "StringTie" in fields[1]
            upstream, downstream = (("five_prime_UTR", "three_prime_UTR") if strand == "+"
                                    else ("three_prime_UTR", "five_prime_UTR"))

            overlapping = [(s, e) for s, e in coding if s <= end and e >= start]
            if overlapping:
                c_start = min(s for s, _ in overlapping)
                c_end = max(e for _, e in overlapping)
                if start < c_start:
                    utr_features.append(_make_utr_feature(fields, upstream, start, c_start - 1))
                if end > c_end:
                    utr_features.append(_make_utr_feature(fields, downstream, c_end + 1, end))
                if not from_stringtie:
                    kept.append(feature)
            elif from_stringtie:
                if end < cds_min:
                    utr_features.append(_make_utr_feature(fields, upstream, start, end))
                elif start > cds_max:
                    utr_features.append(_make_utr_feature(fields, downstream, start, end))
                # a StringTie exon between two CDS segments has no place; dropped
            else:
                kept.append(feature)

        features = kept + _merge_utrs([u for u in utr_features if u])
        features.sort(key=lambda x: int(x.split('\t')[3]))
        tsebra_gtf[transcript_id] = features

    return tsebra_gtf


def rebuild_exons(tsebra_gtf):
    """
    Make the exon lines cover the UTRs.

    In GTF the exon is the transcribed segment, UTR included; the predictor
    exon lines end at the coding region. For every transcript with UTR
    features, each exon becomes the union of the predictor exon and the UTR
    features that overlap or touch it, and a UTR feature apart from all
    predictor exons (a UTR exon behind an intron) gets an exon line of its
    own. The predictor's exon line is kept as template; a UTR-only exon copies
    the first exon line with score '.'. When the transcript has intron lines,
    the gaps between the new exons without one get intron lines too, with
    score '.'. Transcripts without UTR features are left as they are.

    Args:
    - tsebra_gtf (dict): transcript ID -> list of GTF feature lines, after
      compute_utr_features.

    Returns:
    dict: tsebra_gtf with exon (and intron) lines covering the UTRs.
    """
    for transcript_id, features in tsebra_gtf.items():
        exons = [f for f in features if f.split('\t')[2] == "exon"]
        utrs = [f for f in features if f.split('\t')[2] in ("five_prime_UTR", "three_prime_UTR")]
        if not utrs:
            continue
        introns = [f for f in features if f.split('\t')[2] == "intron"]

        spans = sorted((int(f.split('\t')[3]), int(f.split('\t')[4])) for f in exons + utrs)
        merged = []
        for s, e in spans:
            if merged and s <= merged[-1][1] + 1:
                merged[-1][1] = max(merged[-1][1], e)
            else:
                merged.append([s, e])

        if exons:
            template = exons[0].split('\t')
        else:
            template = next(f for f in features if f.split('\t')[2] == "CDS").split('\t')
            template[2] = "exon"
        template[5] = "."
        template[7] = "."
        exon_spans = [(int(f.split('\t')[3]), int(f.split('\t')[4]), f) for f in exons]
        new_exons = []
        for s, e in merged:
            inside = [f for es, ee, f in exon_spans if s <= es and ee <= e]
            fields = inside[0].split('\t') if inside else list(template)
            fields[3] = str(s)
            fields[4] = str(e)
            new_exons.append('\t'.join(fields))

        new_introns = []
        if introns:
            present = {(int(f.split('\t')[3]), int(f.split('\t')[4])) for f in introns}
            intron_template = introns[0].split('\t')
            intron_template[5] = "."
            for (_, e1), (s2, _) in zip(merged, merged[1:]):
                if (e1 + 1, s2 - 1) not in present:
                    fields = list(intron_template)
                    fields[3] = str(e1 + 1)
                    fields[4] = str(s2 - 1)
                    new_introns.append('\t'.join(fields))

        rest = [f for f in features if f.split('\t')[2] != "exon"]
        tsebra_gtf[transcript_id] = sorted(rest + new_exons + new_introns,
                                           key=lambda x: int(x.split('\t')[3]))
    return tsebra_gtf


def fix_feature_coordinates(gtf_dict, gene_dict, tx_to_gene_dict, tx_dict):
    """
    The list of features in gtf_dict has been expanded compared to the original version. We need to identify the left most and right most coordinate
     for each transcript. Then, update the tx_dict lines with these new coordinates. In the end, loop over all tx_dict entries and identify the left most and right
      most coordinate per gene, then update the gene lines in gene_dict.
    
    Args:
    - gtf_dict (dict): Dictionary with transcript IDs as keys and lists of non-gene feature lines as values.
    - gene_dict (dict): Dictionary with gene IDs extracted from the last column of gene feature lines as keys and the corresponding gene line as value.
    - tx_to_gene_dict (dict): Dictionary with transcript IDs as keys and the corresponding gene ID as value, extracted from the last column of transcript feature lines.
    - tx_dict (dict): Dictionary with transcript IDs as keys and the corresponding transcript line as value. The entire last column is used as the transcript ID.

    Returns:
    gene_dict, tx_dict with updated coordinates
    """
    # 1. Update transcript coordinates based on feature coordinates in gtf_dict
    for tx_id, features in gtf_dict.items():
        # Features on another scaffold or strand than the transcript line
        # must not corrupt coordinates; print_gtf drops them.
        tx_line = tx_dict.get(tx_id)
        starts = []
        ends = []
        for feature in features:
            fields = feature.split('\t')
            if tx_line and not same_locus(feature, tx_line):
                continue
            starts.append(int(fields[3]))
            ends.append(int(fields[4]))

        if not starts:
            continue

        # Find the min and max coordinates for the transcript
        min_coord = min(starts)
        max_coord = max(ends)
        
        tx_fields = tx_dict[tx_id].split('\t')
        tx_fields[3] = str(min_coord)
        tx_fields[4] = str(max_coord)
        tx_dict[tx_id] = '\t'.join(tx_fields)
    
    # 2. Update gene coordinates based on updated transcript coordinates in tx_dict
    for gene_id in gene_dict:
        associated_transcripts = [tx for tx, gid in tx_to_gene_dict.items() if gid == gene_id]
        
        starts = []
        ends = []
        for tx_id in associated_transcripts:
            tx_fields = tx_dict[tx_id].split('\t')
            starts.append(int(tx_fields[3]))
            ends.append(int(tx_fields[4]))
        
        # Find the min and max coordinates for the gene
        min_coord = min(starts)
        max_coord = max(ends)
        
        gene_fields = gene_dict[gene_id].split('\t')
        gene_fields[3] = str(min_coord)
        gene_fields[4] = str(max_coord)
        gene_dict[gene_id] = '\t'.join(gene_fields)
    
    return gene_dict, tx_dict


def print_gtf(filename, gtf_dict, gene_dict, tx_to_gene_dict, tx_dict):
    """
    Print GTF lines based on gene_dict and gtf_dict.
    
    Args:
    - filename (str): Path to the output file.
    - gtf_dict (dict): Dictionary with transcript IDs as keys and lists of non-gene feature lines as values.
    - gene_dict (dict): Dictionary with gene IDs extracted from the last column of gene feature lines as keys and the corresponding gene line as value.
    - tx_to_gene_dict (dict): Dictionary with transcript IDs as keys and the corresponding gene ID as value, extracted from the last column of transcript feature lines.
    - tx_dict (dict): Dictionary with transcript IDs as keys and the corresponding transcript line as value. The entire last column is used as the transcript ID.

    Features whose sequence or strand differs from their transcript line are
    dropped, not written (issue #62).

    Returns:
    int: Number of dropped features.
    """
    printed_gene = {}
    dropped = 0
    try:
        with open(filename, 'w') as f:
            # Iterate over gene_dict entries
            for tx_id, tx_line in tx_dict.items():
                gene_id = tx_to_gene_dict[tx_id]
                if gene_id not in printed_gene:
                    # Fix gene line: ensure proper gene_id attribute
                    gene_line = gene_dict[gene_id]
                    gene_fields = gene_line.split('\t')
                    if len(gene_fields) == 9 and 'gene_id' not in gene_fields[8]:
                        gene_fields[8] = f'gene_id "{gene_id}";'
                    f.write('\t'.join(gene_fields) + "\n")
                    printed_gene[gene_id] = True
                # Fix transcript line: ensure proper transcript_id and gene_id attributes
                tx_fields = tx_line.split('\t')
                if len(tx_fields) == 9 and 'transcript_id' not in tx_fields[8]:
                    tx_fields[8] = f'transcript_id "{tx_id}"; gene_id "{gene_id}";'
                f.write('\t'.join(tx_fields) + "\n")
                sorted_features = sorted(gtf_dict.get(tx_id, []), key=lambda x: int(x.split('\t')[3]))
                for feature in sorted_features:
                    if not same_locus(feature, tx_line):
                        dropped += 1
                        continue
                    # UTR lines: source stringtie2utr, only transcript_id and gene_id
                    fields = feature.split("\t")
                    if fields[2] in ("five_prime_UTR", "three_prime_UTR"):
                        f.write(fields[0] + "\tstringtie2utr\t" + "\t".join(fields[2:8]) + "\ttranscript_id \"" + tx_id + "\"; gene_id \"" + tx_to_gene_dict[tx_id] + "\";" + "\n")
                    else:
                        f.write(feature + "\n")
    except IOError:
        print("Could not write to file: " + filename)
        exit(1)
    return dropped

def build_tree(data):
    """Build an interval tree from data. We will use that to quickly find the overlapping single exon genes/transcript pairs."""
    tree = IntervalTree()
    for item in data:
        start, end, value = item
        tree.addi(start, end, value)
    return tree

def construct_transcript_tree(tx_dict):
    """Contructs a dictionary that has sequence name as first key, then strand as second key, and transcript interval tree as value.
    Internally, before calling build_tree(data), a data structure for each sequence and strand must be constructed. It looks like this:
    transcripts = [(50, 550, "tx1"), (580, 950, "tx2")]
    
    Args: 
    - tx_dict (dict): Dictionary with transcript IDs as keys and lists of transcript feature lines as values.
    """
    seq_strand_to_transcripts = {}
    # Parse gtf_dict to segregate transcript data by sequence name and strand
    for transcript_id, transcript_data in tx_dict.items():
        fields = transcript_data.split('\t')
        seq_name = fields[0]
        start = int(fields[3])
        end = int(fields[4])
        strand = fields[6]
        # Use setdefault to initialize a nested dictionary
        seq_strand_dict = seq_strand_to_transcripts.setdefault(seq_name, {})
        # Use setdefault to initialize a list for the current strand
        data_list = seq_strand_dict.setdefault(strand, [])
        data_list.append((start, end, transcript_id))
    
    # Build interval trees for each seq_name-strand combination
    for seq_name, strand_data in seq_strand_to_transcripts.items():
        for strand, data_list in strand_data.items():
            seq_strand_to_transcripts[seq_name][strand] = build_tree(data_list)

    return seq_strand_to_transcripts

def construct_gene_tree(tx_dict, single_exons):
    """Contructs a dictionary that has sequence name as first key, then strand as second key, and transcript interval tree as value.
    Internally, before calling build_tree(data), a data structure for each sequence and strand must be constructed. It looks like this:
    transcripts = [(50, 550, "tx1"), (580, 950, "tx2")]
    
    Args: 
    - tx_dict (dict): Dictionary with transcript IDs as keys and lists of transcript feature lines as values.
    - single_exons (dict): Dictionary with single-exon transcript IDs. We only want to build the tree for single-exon transcripts.
    """
    seq_strand_to_genes = {}
    # Parse tx_dict to segregate gene data by sequence name and strand, but only for single-exon transcripts
    for transcript_id, line in tx_dict.items():
        # Check if the transcript_id is in single_exons
        if transcript_id in single_exons:
            fields = line.split('\t')
            seq_name = fields[0]
            start = int(fields[3])
            end = int(fields[4])
            strand = fields[6]

            # Use setdefault to initialize a nested dictionary
            seq_strand_dict = seq_strand_to_genes.setdefault(seq_name, {})
            # Use setdefault to initialize a list for the current strand
            data_list = seq_strand_dict.setdefault(strand, [])
            data_list.append((start, end, transcript_id))
    
    # Build interval trees for each seq_name-strand combination
    for seq_name, strand_data in seq_strand_to_genes.items():
        for strand, data_list in strand_data.items():
            seq_strand_to_genes[seq_name][strand] = build_tree(data_list)

    return seq_strand_to_genes

def find_overlapping_transcripts(gene_tree, transcript_tree):
    """Find transcripts that overlap with genes."""
    gene_to_transcripts = {}

    # loop over the sequences in outer dict:
    for seq_name, strand_data in gene_tree.items():
        # loop over the strands in the inner dict:
        for strand, gene_tree in strand_data.items():
            # loop over the genes in the gene_tree:
            for gene_interval in gene_tree:
                if seq_name in transcript_tree:
                    if strand in transcript_tree[seq_name]:
                        overlapping_transcripts = transcript_tree[seq_name][strand].overlap(gene_interval.begin, gene_interval.end)
                        if overlapping_transcripts:
                            gene_id = gene_interval.data
                            gene_to_transcripts[gene_id] = [tx.data for tx in overlapping_transcripts]
                    
    return gene_to_transcripts

def extract_introns_from_dict(tx_dict, tx_id):
    """Extract introns directly from stringtie_tx_dict."""
    introns = []
    for feature_line in tx_dict[tx_id]:
        feature_type, start, end = feature_line.split("\t")[2:5]
        if feature_type == "intron":
            introns.append((int(start), int(end)))
    return introns

def check_overlap_compatibility(gene_to_transcripts, tsebra_tx_dict, stringtie_tx_dict):
    """Check if the overlapping transcripts are compatible with the gene models.
    In particular, we want to make sure that no stringtie transcript contains an intron within
    the CDS feature range of the braker transcripts. Only verfy this for those gene/transcript list matches that
    are in gene_to_transcripts. If an intron breaks the gene/transcript association, the transcript should be removed from the list in gene_to_transcripts.
    If the list is empty, also the key should be removed.

    Args:
    - gene_to_transcipts (dict): has transcript IDs from braker as keys and lists of transcript IDs from stringtie as values.
    - tsebra_tx_dict (dict): Dictionary with transcript IDs as keys and the corresponding transcript line as value.
    - stringtie_tx_dict (dict): Dictionary with transcript IDs as keys and the corresponding transcript line as value.

    Returns:
    dict: Updated gene_to_transcripts dictionary.
    """
    for tsebra_tx_id, stringtie_tx_ids in list(gene_to_transcripts.items()):  # Using list() to allow dictionary changes during iteration
        tsebra_tx = tsebra_tx_dict[tsebra_tx_id]
        for line in tsebra_tx:
            if re.search(r'\tCDS\t', line):
                fields = line.split('\t')
                start = int(fields[3])
                end = int(fields[4])
                break # there's only one CDS because it's a single-exon transcript
        # Assuming the CDS range is at the end of the transcript line in the format start-end
        tsebra_cds_start, tsebra_cds_end = [start,end]
        
        # Store compatible transcripts
        compatible_tx = []
        
        for st_tx_id in stringtie_tx_ids:
            tx_id = re.search(r'gene_id "[^"]+"; transcript_id "([^"]+)";', st_tx_id).group(1)
            introns = extract_introns_from_dict(stringtie_tx_dict, tx_id)
            
            # Check if any intron overlaps with the CDS range
            overlap = any(intron_start <= tsebra_cds_end and intron_end >= tsebra_cds_start for intron_start, intron_end in introns)
            
            if not overlap:
                compatible_tx.append(tx_id)
                
        # Update the dictionary
        if compatible_tx:
            gene_to_transcripts[tsebra_tx_id] = compatible_tx
        else:
            del gene_to_transcripts[tsebra_tx_id]
    
    return gene_to_transcripts
    
    
def match_assembly(stringtie_file, tsebra_none_gene_dict, tsebra_introns_hash, seq_strand_to_genes):
    """
    Match BRAKER transcripts to the transcripts of one StringTie assembly.

    Multi-exon transcripts are matched by intron chain, single-exon transcripts
    by overlap (without a StringTie intron inside the CDS). Of several matches,
    the longest StringTie transcript is kept.

    Returns:
    tuple: (BRAKER transcript ID -> StringTie transcript ID,
            StringTie transcript ID -> list of feature lines incl. introns)
    """
    stringtie_none_gene_dict, _, _, stringtie_tx_dict = read_gtf(stringtie_file)
    stringtie_none_gene_dict = add_intron_features(stringtie_none_gene_dict)
    matched_transcripts = find_matching_transcripts(
        tsebra_introns_hash, create_introns_hash(stringtie_none_gene_dict))
    overlaps = find_overlapping_transcripts(
        seq_strand_to_genes, construct_transcript_tree(stringtie_tx_dict))
    # the overlaps might include matches where stringtie introns break cds, remove these
    overlaps = check_overlap_compatibility(overlaps, tsebra_none_gene_dict, stringtie_none_gene_dict)
    matched_transcripts.update(overlaps)
    return (select_longest_tx(matched_transcripts, tx_len(stringtie_none_gene_dict)),
            stringtie_none_gene_dict)


def main():
    parser = argparse.ArgumentParser(description="Updates GaiusAugustus gene models with UTRs from a StringTie assembly.")
    
    # Mandatory input arguments
    parser.add_argument("-g", "--genes", required=True, help="File with gene gene models in GTF format, typically the output of Augustus, BRAKER, or TSEBRA.")
    parser.add_argument("-s", "--stringtie", required=True, help="File with StringTie transcript models in GFF format")
    parser.add_argument("-o", "--output", required=True, help="Output file name, file is in GTF format.")
    parser.add_argument("-l", "--long-read-stringtie",
                        help="Optional StringTie assembly of long reads only (IsoSeq, stringtie -L). "
                             "A BRAKER transcript matched in this assembly takes its UTRs from it, "
                             "even if it also matches a transcript in --stringtie.")
    parser.add_argument("--max-utr-extension", type=int, default=5000,
                        help="Maximum bp a StringTie exon may extend beyond the BRAKER CDS boundary "
                             "on either side.  Prevents polycistronic / read-through assemblies from "
                             "inflating gene coordinates.  Default: 5000.  Set to 0 to disable.")

    args = parser.parse_args()

    # read the tsebra_file with gene models
    tsebra_none_gene_dict, tsebra_gene_line_dict, tsebra_tx_to_gene_dict, tsebra_tx_dict = read_gtf(args.genes)

    # in order to match genes and transcripts efficiently, we will take 2 different approaches. For multi-exon genes,
    # we create intron hashes for matching transcripts. For single-exon genes, we construct interval trees.
    tsebra_introns_hash = create_introns_hash(tsebra_none_gene_dict)
    single_exon_genes = find_single_exon_genes(tsebra_none_gene_dict)
    seq_strand_to_genes = construct_gene_tree(tsebra_tx_dict, single_exon_genes)

    final_matching_tx, stringtie_none_gene_dict = match_assembly(
        args.stringtie, tsebra_none_gene_dict, tsebra_introns_hash, seq_strand_to_genes)
    print(f"{len(final_matching_tx)} transcripts matched in {args.stringtie}", file=sys.stderr)

    # Long-read matches replace short-read matches (#29 follow-up): short-read
    # StringTie joins neighbouring genes more often than long reads do.
    if args.long_read_stringtie:
        lr_matching_tx, lr_none_gene_dict = match_assembly(
            args.long_read_stringtie, tsebra_none_gene_dict, tsebra_introns_hash, seq_strand_to_genes)
        replaced = sum(1 for tx in lr_matching_tx if tx in final_matching_tx)
        # prefix long-read IDs, both assemblies number their transcripts MSTRG.*
        stringtie_none_gene_dict.update(
            {"longread:" + st: feats for st, feats in lr_none_gene_dict.items()})
        final_matching_tx.update(
            {tx: "longread:" + st for tx, st in lr_matching_tx.items()})
        print(f"{len(lr_matching_tx)} transcripts matched in {args.long_read_stringtie} "
              f"(UTRs taken from there; {replaced} of them replace a match in "
              f"{args.stringtie})", file=sys.stderr)

    # UTRs must not run into a neighbour gene that has transcript support itself (#29)
    bounds = neighbour_bounds(tsebra_none_gene_dict, tsebra_tx_to_gene_dict, final_matching_tx)
    n_stopped = 0
    for tx, st in final_matching_tx.items():
        if tx not in bounds:
            continue
        lo, hi = bounds[tx]
        ref = tsebra_none_gene_dict[tx][0]
        for e in stringtie_none_gene_dict[st]:
            ef = e.split('\t')
            if ef[2] == 'exon' and same_locus(e, ref) and (
                    (lo is not None and int(ef[3]) < lo) or (hi is not None and int(ef[4]) > hi)):
                n_stopped += 1
                break
    print(f"{n_stopped} transcripts: UTR stopped at a transcript-supported neighbour gene",
          file=sys.stderr)

    # merge features from stringtie_gtf into tsebra_gtf based on the selected transcripts, this is a simple concatenation,
    # UTR features are not inferred, yet
    tsebra_gtf = merge_features(tsebra_none_gene_dict, stringtie_none_gene_dict, final_matching_tx,
                                max_utr_extension=args.max_utr_extension, bounds=bounds)
    # compute UTR features, remove StringTie exon features
    tsebra_gtf = compute_utr_features(tsebra_gtf)
    # exon lines cover the UTRs, as GTF expects
    tsebra_gtf = rebuild_exons(tsebra_gtf)

    # expanding gene/transcripts by UTRs shifts the coordinates of these features, we need to update the coordinates in the gene and transcript lines
    tsebra_gene_line_dict, tsebra_tx_dict = fix_feature_coordinates(tsebra_gtf, tsebra_gene_line_dict, tsebra_tx_to_gene_dict, tsebra_tx_dict)

    # print the updated tsebra_gtf
    dropped = print_gtf(args.output, tsebra_gtf, tsebra_gene_line_dict, tsebra_tx_to_gene_dict, tsebra_tx_dict)
    if dropped:
        print(f"Dropped {dropped} features on another sequence or strand than "
              f"their transcript", file=sys.stderr)

if __name__ == "__main__":
    main()
